- name: configure MYSQL
  hosts: mysql
  become: yes
  tasks:
  - name: "Install MySQL"
    ansible.builtin.package:
      name: mysql-server
      state:  installed
  - name: "Start and Enable MySQL"
    ansible.builtin.service:
      name: mysqld
      state:  started
      enabled:  yes
  - name: Set PW
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "172.31.27.46"
    register: "mysql_info"